### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by rashtisouciance** [xuqingfeng/ansible-kapacitor#1]
Getting this error when running your role:

` {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/home/jenkins-slave/workspace/BRANCH-CD-EXPERIMENT-TEST/deploy/provision/roles/xuqingfeng.kapacitor/tasks/configure.yml': line 22, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy all tick files\n  ^ here\n"}`

**Comment by xuqingfeng** [comment]
Thank you for raising it.
